import pandas as pd
table1 = pd.DataFrame({"ID": [1, 2, 3]})
table2 = pd.DataFrame({"NAME": ["A", "B"]})
print('')
print('')
print("----------------TABLE 1--------------------")
print('')
print('')
print(table1)
print("----------------TABLE 2--------------------")
print('')
print('')
print(table2)
print("-------------TABLE 1 & TABLE 2 JOIN--------------")
print('')
print('')
df = table1.join(table2)
print(df)
